color: null
fieldLayouts:
  b0633844-e346-46b0-85ac-d1b03dac80b0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8f4d856b-ff8d-4ce8-9ae3-b4b2dd3e975c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 69856e10-99a9-4a55-a17b-20962a29697d # Hoofdtekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c109aef-3d32-4184-acbb-e5f5350f7adf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5e86435c-5010-4dfa-8280-d64714aeed73 # formfield
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59acf239-242c-4b41-be90-64d27a097d8f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d97e7f11-a688-489a-9c2b-fa3c855a593c
        userCondition: null
handle: formBlock
hasTitleField: true
icon: ''
name: 'Form Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
