color: null
fieldLayouts:
  f28c0313-305d-48b4-b52d-73ff5dc81f94:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0db0b1f1-9af3-4d67-b71a-9d3a1ae74483
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a8a90462-1ea1-45bb-9fb1-2d1211ed734a # producten2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3d0f324-1fd4-43dc-940d-44fd410298b6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 53ee0c2d-33eb-4612-8886-89c1a1c1fd6c
        userCondition: null
handle: producten2
hasTitleField: true
icon: ''
name: Producten2
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
