color: null
fieldLayouts:
  14d75722-3415-4ed0-a9f8-bc2f6989af54:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e2e0c045-345f-414f-bd8a-aaebeea75d16
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2b278c4c-202a-4ca4-8a43-624a6e3a218a
        userCondition: null
handle: productOverzicht
hasTitleField: true
icon: ''
name: 'product overzicht'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
