color: null
fieldLayouts:
  348155ea-18bb-4784-a8e8-a6e53c9054f2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 32fcfd4a-2283-4e84-a957-18b00d2a81f7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 395565b2-6aaa-48c5-8326-03d6ca6f954d
        userCondition: null
handle: productenOverzicht
hasTitleField: true
icon: ''
name: 'producten overzicht'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
