color: null
fieldLayouts:
  0c3d8832-b0cd-4237-8b68-fd8c21eff573:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7c787aa1-8b96-4e74-8bdc-66dfe7ba3702
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 242bdf42-c845-4ea9-9aa7-713eb90dd885
        userCondition: null
handle: producten
hasTitleField: true
icon: ''
name: Producten
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
