color: null
fieldLayouts:
  f1653245-cb22-4938-a097-4328347b8e08:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 10be5c6d-e468-4845-875f-fa5e74be0036
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bf6f36b8-d33d-42b1-9184-f0009c62d623 # Hoofdtitel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea486abe-0ce2-491e-a0ef-504e19b0429c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 69856e10-99a9-4a55-a17b-20962a29697d # Hoofdtekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d14019ac-7a0a-44a5-a0a0-5dd2242966ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 547246a6-9ca7-4c8a-ba25-a7f5f7d4d49a # Hoofdbutton
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c14e9009-dcb4-4c73-91b4-9d97bfae1441
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d5adc84-159d-4815-a7b0-209aff3e442f # Afbeelding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3222dcff-d51b-4f25-830b-5d765ad7ca93
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e628c71e-0d55-4873-b0bd-d8516b1ff9cd # Populaire producten
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55ebd035-9fa2-45ff-9745-3068b972d7f7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 797ac42c-be97-4603-bc28-225b3e0bff15 # Afbeelding2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 317c8f16-2bb1-4f1c-a523-a1789c2b21f8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 869e97c5-e745-4002-aa22-876a0ab833c6 # titel2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc0a6ed3-8c4e-4a70-b4ca-69bf879af104
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b7db6fff-ee95-4591-a572-1d6f25cf3b25 # cardtitel1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1847802c-34fd-4c35-b293-89deac9af8ab
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 955e9fac-3a53-4cdb-a2dc-adf6ec33b4a2 # cardtekst1
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04bd088b-83e1-4298-9db2-6335262eab79
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ab87770-18f6-4aa4-a8b7-98c122dd4a1a # cardtitel2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e16d299-2770-4b12-b35c-e6e80df94a76
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b997dfda-cd6c-4275-805e-34ff8e8feec2 # cardtekst2
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00020379-b1bc-4627-920a-4baf29e5f13c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9632beff-e61b-4270-8675-77dcfde1d40e # cardtitel3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffd55714-74bf-4295-99f3-099e0a5ea4a8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 61f7feb4-4694-484c-893e-fb9a9c007428 # cardtekst3
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59cead82-bd23-456f-9976-6328aac3bfdd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2250ad0c-8e5c-4167-afe0-e9fffb42197f # Contact Titel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87c87111-8ed5-4e49-9225-8dede37d72b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2250ad0c-8e5c-4167-afe0-e9fffb42197f # Contact Titel
            handle: contactTitel2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5e81054-2caf-4cde-89d1-e67d06f43d84
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f9a4255-b8ae-40ea-8649-cf456b33e30c # Contact Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa483934-2518-4f03-9cdd-5f064ed0d8d2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7b210708-1dec-4de0-963a-62f27ed296de
        userCondition: null
handle: startpagina
hasTitleField: true
icon: house
name: startpagina
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
