color: null
fieldLayouts:
  f1653245-cb22-4938-a097-4328347b8e08:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bf6f36b8-d33d-42b1-9184-f0009c62d623 # Hoofdtitel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea486abe-0ce2-491e-a0ef-504e19b0429c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d5adc84-159d-4815-a7b0-209aff3e442f # Afbeelding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae7a04bc-b00d-4b00-a64a-9d9e9389559f
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 10be5c6d-e468-4845-875f-fa5e74be0036
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7b210708-1dec-4de0-963a-62f27ed296de
        userCondition: null
handle: startpagina
hasTitleField: true
icon: house
name: startpagina
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
