color: null
fieldLayouts:
  567056c1-a47b-4c5c-8eef-13367728f575:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c3850160-4fb0-4d0c-af4a-175503eaf931
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d5adc84-159d-4815-a7b0-209aff3e442f # Afbeelding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2471f63-b586-4b20-98b4-ffb3edb0b16e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 69856e10-99a9-4a55-a17b-20962a29697d # Hoofdtekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 615da2fb-2f91-4bc2-9440-2d1afaac49ba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 36664aed-f0f3-4e8b-9bfb-feee11fde10f # Afbeeldign Positie
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e01a97b4-9680-4c23-b2df-c4a211a59380
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8f84e9c2-b78d-49e3-8e71-c72bf6520a8f # Show title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: febe31e8-7b00-438c-8ff4-721472f02cc5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b09f2a8a-c5ff-4c57-8726-b6dc88475c1a
        userCondition: null
handle: tekstAfbeelding
hasTitleField: true
icon: ''
name: 'tekst + afbeelding'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
