columnSuffix: null
handle: afbeeldignPositie
instructions: null
name: 'Afbeeldign Positie'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - ''
        -
          - value
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
