columnSuffix: null
handle: afbeelding
instructions: null
name: Afbeelding
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:c2f2127e-f0a9-4c4b-a158-b709d02cbef5' # afbeeldingen
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: 1
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:c2f2127e-f0a9-4c4b-a158-b709d02cbef5' # afbeeldingen
  restrictedLocationSubpath: null
  selectionLabel: 'Voeg Hero afbeelding toe'
  showCardsInGrid: false
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:c2f2127e-f0a9-4c4b-a158-b709d02cbef5' # afbeeldingen
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
