columnSuffix: null
handle: kost
instructions: null
name: Kost
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  selectionLabel: 'Voeg toe'
  showCardsInGrid: false
  showSiteMenu: true
  sources:
    - 'section:5cb4a46a-6325-4bb1-b942-dfd12375193c' # kosten
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
