dateModified: 1715006655
email:
  fromEmail: frederic.steegmans@student.pxl.be
  fromName: 'Crystal Nexus'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    2e7d7668-a91d-4a34-a51a-8f30daf55386: 'Crystal Nexus' # Crystal Nexus
    cd90f7c3-4c21-4827-970f-dce47c74c709: 'Crystal Nexus' # Crystal Nexus
system:
  edition: solo
  live: true
  name: 'Crystal Nexus'
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
