defaultPlacement: end
enableVersioning: true
entryTypes:
  - 728cc3a1-fbd8-42aa-aefa-36586c81993b # contact
handle: contact
maxAuthors: 1
name: contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2e7d7668-a91d-4a34-a51a-8f30daf55386: # Crystal Nexus
    enabledByDefault: true
    hasUrls: true
    template: _contact.twig
    uriFormat: contact
type: single
