defaultPlacement: end
enableVersioning: true
entryTypes:
  - 81fb0060-c7d6-4b0a-a934-6411a532d006 # Custom Page
handle: customPage
maxAuthors: 1
name: 'Custom Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2e7d7668-a91d-4a34-a51a-8f30daf55386: # Crystal Nexus
    enabledByDefault: true
    hasUrls: true
    template: _custom-pages.twig
    uriFormat: custom-page
type: single
