defaultPlacement: end
enableVersioning: true
entryTypes:
  - 70ec348f-2dcc-4486-8263-b7204a10e978 # producten overzicht
handle: productOverzicht
maxAuthors: 1
name: 'product overzicht'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2e7d7668-a91d-4a34-a51a-8f30daf55386: # Crystal Nexus
    enabledByDefault: true
    hasUrls: true
    template: _products.twig
    uriFormat: product-overzicht
type: single
