defaultPlacement: end
enableVersioning: true
entryTypes:
  - efd14935-aca0-4f14-b352-90e0eeb2fe09 # product overzicht
handle: productOverzicht
maxAuthors: 1
name: 'product overzicht'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  2e7d7668-a91d-4a34-a51a-8f30daf55386: # Crystal Nexus
    enabledByDefault: true
    hasUrls: true
    template: _products.twig
    uriFormat: producten
type: single
